#  飞书配置
BASE_URL: https://open.feishu.cn
APP_ID:
APP_SECRET: 
APP_ENCRYPT_KEY: 
APP_VERIFICATION_TOKEN: 
BOT_NAME: CHATGPT

# OpenRouter API配置
OPENAI_KEY: 
OPENAI_MODEL: openai/gpt-4o
OPENAI_MAX_TOKENS: 2000
OPENAI_HTTP_CLIENT_TIMEOUT: 550

# 服务器配置 (生产环境)
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem

# OpenRouter API地址
API_URL: https://openrouter.ai/api/v1
HTTP_PROXY: ""
STREAM_MODE: true

# OpenRouter特有配置
OPENROUTER_SITE_URL: https://feishu-openai-bot.example.com
OPENROUTER_SITE_NAME: Feishu OpenAI Bot
USE_OPENROUTER: true
